### ISSUE TITLE
Add in Higher Taxonomy (family, order) from scientific name

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortalAPI#11]
this was part of the original taxonomy script request but important enough for an issue of its own (and I dont see these in the latest csv). probably should happen after name clean-up and synonomies applied!

**Comment by jdeck88** [comment]
I'm assuming the higher taxonomy is simply adding "order" and "family" and pulling these from the amphib_names.json file?

**Comment by mkoo** [comment]
Yes exactly!

**Comment by jdeck88** [comment]
I added higher level taxonomy to scientificName_list.json  ... it could conceivably go in other places as well.. let me know where @birbjam
