### ISSUE TITLE
synonymy fail?

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortalAPI#12]
Found this in the latest dump (7/26)
 - Pseudacris regilla (count=880) should be Hyliola regilla
(appears correct in JSON)

 - Lithobates catesbeianus (count=171) should be Rana catesbeiana
(I'm a little confused since the portal dashboard seems to apply the synonymy correctly; why not in the csv?)

**Comment by jdeck88** [comment]
the scientificName was updated but not the genus and species.... this was good enough to fix the scientificname_list.json file but not the others... i updated genus & species with the new taxonomy.  all good now.

**Comment by mkoo** [comment]
yay!
