### ISSUE TITLE
Missing project #319 json file

### ISSUE THREAD

**Issue by birbjam** [BNHM/AmphibiaWebDiseasePortalAPI#15]

**Comment by jdeck88** [comment]
a bit more information?

**Comment by birbjam** [comment]
there is no json file for that project

**Comment by mkoo** [comment]
He might have just uploaded this (where do you see that info?) so maybe the harvester has not yet caught up?

**Comment by birbjam** [comment]
https://amphibiandisease.org/projects/?id=319

It just needs a scientificName_projectId_319.json
