### ISSUE TITLE
need: retain verbatim taxonomy

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortalAPI#16]
During taxonomy checking, new fields should be added for the proper taxonomy so we can retain verbatim taxonomy (or instead append original fields with orig_ or similar so we can distinguish in future). This is going to be a critical issue for some since they need to be aligned with original publications etc.

**Comment by jdeck88** [comment]
i've added a verbatimScientificName field to scientificname_listing.json
not sure if we need this field elsewhere or if its ok in just this list.

@mkoo can you let me know where you want to view verbatim scientificName on the UI and i can check the API calls to be sure that we can get this information in the proper place?

**Comment by mkoo** [comment]
I dont know if we need it in the UI _yet_ 
This has implications for things like Futres too. Because we will and are dealing w/ legacy data with legacy names we really should retain this info. So should be included in downloaded datasets. But if you mean UI like the dynamic charting, then I think we do not need to include. (so no changes to majority of the API)

**Comment by jdeck88** [comment]
ok, i'll close issue since for the API it is done.
