### ISSUE TITLE
error in Dashboard: not adding both Bd and Bsal positive samples together

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortalAPI#26]
Addition! @jdeck88 I think this is an API bug so can this be fixed easily?

![Firefox_Screenshot_2021-09-03T15-43-40 421Z](https://user-images.githubusercontent.com/2523089/132032974-1ac8af29-1398-4535-902f-14e6381cc457.png)

**Comment by jdeck88** [comment]
resolved but created a new issue in the UI codebase to make code more resilient: 
https://github.com/BNHM/AmphibiaWebDiseasePortal/issues/129
