### ISSUE TITLE
Taxonomy sanitizer and migration vetting?

### ISSUE THREAD

**Issue by mkoo** [BNHM/AmphibiaWebDiseasePortalAPI#7]
A couple of issues keep coming up with scientific names that I wonder would benefit from a data migration tool so that API served names are clean:
1) check names against the AmphibiaWeb taxonomy (Diana @birbjam is working on accessing the nightly dataset) to make sure it exists, misspellings etc
2) add in order and family from the AW taxonomy
3) update any name changes with the synonomy field
4) fill in Scientificname field by concatenating Genus+Specificepithet fields
(addresses https://github.com/BNHM/AmphibiaWebDiseasePortal/issues/49)
5) check capitalization (Genus in title caps and Specificepithet in lower case) which then would avoid having species listed twice in the species charts see Taricha granulosa and Taricha torosa:

![Firefox_Screenshot_2020-06-24T22-53-31 287Z](https://user-images.githubusercontent.com/2523089/85635892-db79c780-b633-11ea-8594-0f9fb8e26e66.png)

Interested to hear how to handle these issues

**Comment by mkoo** [comment]
Add another rule for "sp" in Specificepithet since it shows up with and without periods= remove "sp", "sp." and "cf", "cf." from Specificepithet.

**Comment by jdeck88** [comment]
We decided that we would build a python script for checking the AmphibiaWeb Taxonomy for validating species names AND filling in synonymies with currently accepted names.    The API would return results just on currently accepted name.   
Process:
1. First adjust capitalization issues on the fly.
2. Synonymy translation.
3. Finally, report outright bad names into a file that could be linked to via the API (bad names by project).  This would be mispelling

Current AmphibiaWeb file with taxonomy names is at: https://amphibiaweb.org/amphib_names.json
@JoyceGross needs to add synonyms.

**Comment by jdeck88** [comment]
This is pretty much done... i'm moving "Finally, report outright bad names into a file that could be linked to via the API (bad names by project). This would be mispelling" to a new issue... not sure it is as high a priority as others...
Also, i spent awhile on "synonomy translation" only to realize that there are no old taxonomic names... anyway, at least there is a translation in place for that.
